name: Bug report
description: File a bug report
title: 'Bug:'
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thank you for filing a bug report! 🐛"
  - type: dropdown
    attributes:
      label: Which crate is this issue about?
      multiple: true
      options:
        - "windows"
        - "windows-sys"
        - "other (please share in the comments)"
  - type: input
    attributes:
      label: Crate Version
      description: What is the version of the crate you're using?
      placeholder: You can find the exact crate version in your `Cargo.lock` file.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Summary
      description: >
        Please provide a short summary of the bug, along with any information
        you feel relevant to replicating the bug.
      value: |
        ```rust
        <code>
        ```
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: "I expected to see this happen:"
      placeholder: "*explanation*"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual Behavior
      description: "Instead, this happened:"
      placeholder: "*explanation*"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Comments
      description: Is there anything else you'd like to share?
    validations:
      required: false
