blank_issues_enabled: false
contact_links:
  - name: Windows API Question
    url: https://stackoverflow.com/questions/tagged/winapi
    about: Please ask and answer questions about Windows API usage on StackOverflow.
